### ISSUE TITLE
download and install issues

### ISSUE THREAD

**Issue by butterp1** [Bloke/ext_captcha#1]
Hi Bloke,
hoping to give this a spin, installing the 4.8 way. 
The download link on the github page goes to a 404.
Downloaded the zip via the code dropdown and could not add to TXP plugins page as got "Badly formed or empty plugin code." in red. Assuming that isn't the right zip to be using for this?

**Comment by Bloke** [comment]
Ooops, so sorry. The format that GitHub keeps the project in isn't compatible with our zip file format required for uploading. I've [added one to the codebase](https://github.com/Bloke/ext_captcha/blob/main/ext_captcha.zip) for you.
